name: HelloGithub

on:
  schedule:
    - cron: '50 * * * *'

jobs:
 my_job:
  runs-on: ubuntu-latest
  steps:
    - name: scrpit1
      run: echo Hello Github!
 
    - name: script2
      run: curl -H "Accept-Language:zh-CN" -o result.html wttr.in/suzhou #获取苏州市天气
